# Crowdin configuration for Morphe
# https://support.crowdin.com/configuration-file/

project_id_env: "CROWDIN_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"

# Preserve hierarchy in Crowdin
preserve_hierarchy: true

files:
  # Main translation file
  - source: /public/locales/en.json
    translation: /public/locales/%locale_with_underscore%.json

    # Language mapping for region codes
    languages_mapping:
      locale_with_underscore:
        # Brazilian Portuguese
        pt-BR: pt-BR
        # European Portuguese
        pt-PT: pt-PT
        # Ukrainian
        uk-UA: uk-UA
        # Spanish
        es: es
        # German
        de: de
        # French
        fr: fr
